{{- if not .Values.tls.auto }}
apiVersion: v1
kind: Secret
metadata:
  name: kube-valet
  namespace: kube-valet
data:
  server.pem: {{ .Files.Get .Values.tls.certPath | b64enc }}
  server-key.pem: {{ .Files.Get .Values.tls.keyPath | b64enc }}
{{- end }}
