# This is a very simple example that makes all pods with the label worktype=simple schedule to nodes with a label of for-worktype=simple
apiVersion: assignments.kube-valet.io/v1alpha1
kind: ClusterPodAssignmentRule
metadata:
  name: simple
spec:
  targetLabels:
    worktype: "simple"
  scheduling:
    nodeSelector:
      for-worktype: "simple"
